name: Node.js CI

on:
  push:
    branches:
      - "**" # Run on all branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install && npm run-script build

    - name: Netlify Actions
      if: github.ref == 'refs/head/main'
      # You may pin to the exact commit or the version.
      # uses: nwtgck/actions-netlify@db90f8c196ec8808d9765741da1be62c48db8867
      uses: nwtgck/actions-netlify@v1.1.11
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        publish-dir: ./build
        deploy-message: "Auto-deployed from GitHub"
